password = "rods"
server_version = "4.3.0"
can_write_pam_pass = false
resources = ["bundleResc", "demoResc"]
free_resources = [false, false]
env_path = "/root/.irods/irods_environment.json"
test_user = "testuser"
environment = "iRODS 4.3.0"
